# Regenerated by `mix spark.formatter` from the DSL extensions — do not hand-edit.
spark_locals_without_parens = [
  actions: 1,
  event: 1,
  event: 2,
  producer: 1,
  source_resource: 1,
  version: 1,
  version: 2
]

# Non-Spark locals (e.g. the router macro) — kept separate so `mix spark.formatter`
# regeneration of the list above doesn't drop them.
extra_locals_without_parens = [
  ash_integration_dashboard: 1,
  ash_integration_dashboard: 2
]

locals_without_parens = spark_locals_without_parens ++ extra_locals_without_parens

[
  import_deps: [
    :ash,
    :ash_postgres,
    :ash_cloak,
    :ash_phoenix,
    :spark,
    :phoenix,
    :phoenix_live_view
  ],
  inputs: ["*.{ex,exs}", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter, Phoenix.LiveView.HTMLFormatter],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
