defmodule Example.DataCase do
  @moduledoc """
  This module defines the setup for tests requiring
  access to the application's data layer.

  You may define functions here to be used as helpers in
  your tests.

  Finally, if the test case interacts with the database,
  we enable the SQL sandbox, so changes done to the database
  are reverted at the end of every test. If you are using
  PostgreSQL, you can even run database tests asynchronously
  by setting `use Example.DataCase, async: true`, although
  this option is not recommended for other databases.
  """

  use ExUnit.CaseTemplate

  alias AshIntegration.Outbound.Dispatch.Acknowledger
  alias AshIntegration.Outbound.Dispatch.Relay
  alias AshIntegration.Outbound.Dispatch.Dispatcher

  alias AshIntegration.Outbound.Delivery.Acknowledger, as: DeliveryAcknowledger
  alias AshIntegration.Outbound.Delivery.Relay, as: DeliveryRelay
  alias AshIntegration.Outbound.Delivery.Dispatcher, as: DeliveryDispatcher

  using do
    quote do
      alias Example.Repo

      import Ecto
      import Ecto.Changeset
      import Ecto.Query
      import Example.DataCase
    end
  end

  setup tags do
    Example.DataCase.setup_sandbox(tags)
    :ok
  end

  @doc """
  Sets up the sandbox based on the test tags.
  """
  def setup_sandbox(tags) do
    pid = Ecto.Adapters.SQL.Sandbox.start_owner!(Example.Repo, shared: not tags[:async])
    on_exit(fn -> Ecto.Adapters.SQL.Sandbox.stop_owner(pid) end)
  end

  @doc """
  Build an `EventDelivery` (and its upstream immutable `Event`) for a subscription
  — the split-model replacement for tests that created one combined "event" row.
  Overrides route to whichever side owns the field: `state`/`delivery`/`last_error`
  → the delivery; `event_key` → both (the lane key); `data` (or legacy `snapshot`)
  / `source_*` → the immutable Event. Returns the `EventDelivery`.

  The Event's UUIDv7 `id` (the occurrence-order key) is generated by the database,
  so insertion order determines ordering: create the older event first.
  """
  def build_delivery!(subscription, overrides \\ %{}) do
    o = Map.new(overrides)
    event_key = Map.get(o, :event_key, "p1")
    data = Map.get(o, :data, Map.get(o, :snapshot, %{}))

    event =
      AshIntegration.event_resource()
      |> Ash.Changeset.for_create(
        :create,
        %{
          event_type: subscription.event_type,
          version: subscription.version,
          event_key: event_key,
          source_resource: Map.get(o, :source_resource, "widget"),
          source_resource_id: Map.get(o, :source_resource_id, "r1"),
          source_action: Map.get(o, :source_action, "update"),
          data: data,
          # A delivery exists ⇒ this event was dispatched. Stamp it (unless a test
          # overrides) so the scheduler high-water gate doesn't treat these directly
          # seeded events as still-in-outbox and block their lanes.
          dispatched_at: Map.get(o, :dispatched_at, DateTime.utc_now())
        },
        authorize?: false
      )
      |> Ash.create!(authorize?: false)

    state = Map.get(o, :state, :pending)

    AshIntegration.event_delivery_resource()
    |> Ash.Changeset.for_create(
      :create,
      %{
        event_id: event.id,
        event_type: subscription.event_type,
        version: subscription.version,
        event_key: event_key,
        delivery: Map.get(o, :delivery, %{"x" => 1}),
        # Present only for `suppress_unchanged` subscriptions; drives the scheduler's
        # per-row-vs-bulk split for `:pending` heads. Nil (the common case) otherwise.
        body_hash: Map.get(o, :body_hash),
        state: state,
        last_error: Map.get(o, :last_error),
        subscription_id: subscription.id,
        connection_id: subscription.connection_id
      },
      authorize?: false
    )
    # Mirror the `:deliver` action, which stamps `delivered_at` on a delivered row.
    |> Ash.Changeset.force_change_attribute(
      :delivered_at,
      delivered_at_for(state, o)
    )
    |> Ash.create!(authorize?: false)
  end

  defp delivered_at_for(_state, %{delivered_at: at}), do: at
  defp delivered_at_for(:delivered, _o), do: DateTime.utc_now()
  defp delivered_at_for(_state, _o), do: nil

  @doc """
  Seed a per-attempt delivery `Log` for a subscription — the bottom of the runtime
  drill-down (Event → Delivery → Log) that the delivery relay writes on each attempt.
  Seeded directly (bypassing the relay) so a test can pin `status`, `created_at`
  (for the Logs view's time-window filter), `duration_ms`, `response_status`, and the
  owning `event_delivery_id`. Connection/subscription/event_type default off the
  subscription. Returns the `Log`.
  """
  def build_log!(subscription, overrides \\ %{}) do
    o = Map.new(overrides)

    AshIntegration.delivery_log_resource()
    |> Ash.Seed.seed!(%{
      event_type: Map.get(o, :event_type, subscription.event_type),
      version: subscription.version,
      event_key: Map.get(o, :event_key, "p1"),
      status: Map.get(o, :status, :success),
      response_status: Map.get(o, :response_status),
      duration_ms: Map.get(o, :duration_ms),
      error_message: Map.get(o, :error_message),
      connection_id: subscription.connection_id,
      subscription_id: subscription.id,
      event_delivery_id: Map.get(o, :event_delivery_id),
      created_at: Map.get(o, :created_at, DateTime.utc_now())
    })
  end

  @doc """
  Synchronously drain the outbox by driving the **real Broadway relay callbacks**
  in-process (claim → `prepare_messages` → `handle_message` → `handle_batch` → ack),
  looping until the outbox is empty. This exercises the actual dispatch path —
  batched `project`, the Lua transform, and the atomic `:dispatch` transaction —
  deterministically and on the test's own sandbox connection, with no Broadway
  runtime to allow. (The async pipeline itself is covered by a dedicated test that
  starts an isolated relay via `start_supervised!/1`.)
  """
  def drain_dispatch! do
    # Claim a generous chunk per pass; the loop drains the rest regardless.
    case Dispatcher.claim(100) do
      [] ->
        :ok

      events ->
        events
        |> Enum.map(&dispatch_message/1)
        |> Relay.prepare_messages(%{})
        |> Enum.map(&Relay.handle_message(:default, &1, %{}))
        |> then(&Relay.handle_batch(:default, &1, %{}, %{}))
        |> ack_messages()

        drain_dispatch!()
    end
  end

  defp dispatch_message(event) do
    %Broadway.Message{data: event, acknowledger: Acknowledger.for_event(event.id)}
  end

  defp ack_messages(messages) do
    {successful, failed} = Enum.split_with(messages, &(&1.status == :ok))
    Acknowledger.ack(:ash_integration_dispatch, successful, failed)
  end

  @doc """
  Synchronously execute the delivery outbox by driving the **real delivery relay
  callbacks** in-process (claim → `handle_message` → per-connection `handle_batch`
  → ack), looping until no DUE `:scheduled` row remains. Mirrors `drain_dispatch!`
  on the delivery side: it exercises the actual claim (lease + attempts-on-claim),
  the transport send (stubbed via `Req.Test`), and the `:deliver` /
  `:record_attempt_error` / `:reset_to_pending` bookkeeping with the lease-token
  fence — deterministically, on the test's own sandbox connection, with no Broadway
  runtime to allow.

  Note: a failed delivery stays `:scheduled` with `next_attempt_at` in the future
  (backoff), so it is NOT re-claimed within the same drain — the loop terminates.
  """
  def drain_delivery! do
    case DeliveryDispatcher.claim(100) do
      [] ->
        :ok

      deliveries ->
        deliveries
        |> Enum.map(&delivery_message/1)
        |> Enum.map(&DeliveryRelay.handle_message(:default, &1, %{}))
        # Group per connection (batch_key), exactly as Broadway's batcher would, so
        # each `handle_batch` sees a single-connection batch.
        |> Enum.group_by(& &1.batch_key)
        |> Enum.each(fn {_connection_id, messages} ->
          :default
          |> DeliveryRelay.handle_batch(messages, %{}, %{})
          |> ack_delivery_messages()
        end)

        drain_delivery!()
    end
  end

  defp delivery_message(delivery) do
    %Broadway.Message{
      data: delivery,
      acknowledger: DeliveryAcknowledger.for_delivery(delivery.id)
    }
  end

  defp ack_delivery_messages(messages) do
    {successful, failed} = Enum.split_with(messages, &(&1.status == :ok))
    DeliveryAcknowledger.ack(:ash_integration_delivery, successful, failed)
  end

  @doc """
  Re-run one Event's dispatch — the test analogue of the operator "re-dispatch"
  action: un-stick the Event via its `:reset_dispatch` code interface, then drain
  in-process (no relay runs in test). Idempotent: an already-dispatched Event has
  `dispatched_at` set, so the drain's claim skips it — no duplicate deliveries, no
  state reset.
  """
  def run_dispatch!(event_id) do
    AshIntegration.event_resource()
    |> Ash.get!(event_id, authorize?: false)
    |> Ash.Changeset.for_update(:reset_dispatch, %{}, authorize?: false)
    |> Ash.update!(authorize?: false)

    drain_dispatch!()
  end

  def errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {message, opts} ->
      Regex.replace(~r"%{(\w+)}", message, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end
end
