defmodule Example.Repo.Migrations.AddNotifyOnEveryChange do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_integrations) do
      add :notify_on_every_change, :boolean, default: false
    end
  end

  def down do
    alter table(:outbound_integrations) do
      remove :notify_on_every_change
    end
  end
end
