defmodule Example.Repo.Migrations.AddSuppressionColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_subscriptions) do
      add :suppress_unchanged, :boolean, default: false
    end

    alter table(:outbound_event_deliveries) do
      add :body_hash, :text
    end
  end

  def down do
    alter table(:outbound_event_deliveries) do
      remove :body_hash
    end

    alter table(:outbound_subscriptions) do
      remove :suppress_unchanged
    end
  end
end
