defmodule Example.Repo.Migrations.DropConsecutiveFailures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_subscriptions) do
      remove :consecutive_failures
    end

    alter table(:outbound_connections) do
      remove :consecutive_failures
    end
  end

  def down do
    alter table(:outbound_connections) do
      add :consecutive_failures, :bigint, null: false, default: 0
    end

    alter table(:outbound_subscriptions) do
      add :consecutive_failures, :bigint, null: false, default: 0
    end
  end
end
