defmodule Example.Repo.Migrations.DeliveryFailedStateAndTerminalReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
                     name: "idx_event_deliveries_schedulable_lane"
                   )

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key],
                     name: "idx_one_scheduled_per_connection_event_key"
                   )

    alter table(:outbound_event_deliveries) do
      add :terminal_reason, :text
    end

    create index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
             name: "idx_event_deliveries_schedulable_lane",
             where: "state IN ('pending', 'parked', 'failed')"
           )

    create index(:outbound_event_deliveries, [:connection_id, :event_key],
             name: "idx_one_scheduled_per_connection_event_key",
             unique: true,
             where: "state IN ('scheduled', 'failed')"
           )
  end

  def down do
    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key],
                     name: "idx_one_scheduled_per_connection_event_key"
                   )

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
                     name: "idx_event_deliveries_schedulable_lane"
                   )

    alter table(:outbound_event_deliveries) do
      remove :terminal_reason
    end

    create index(:outbound_event_deliveries, [:connection_id, :event_key],
             name: "idx_one_scheduled_per_connection_event_key",
             unique: true,
             where: "state = 'scheduled'"
           )

    create index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
             name: "idx_event_deliveries_schedulable_lane",
             where: "state IN ('pending', 'parked')"
           )
  end
end
