defmodule Example.Repo.Migrations.AddLogFailureClassAndHealthIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_delivery_logs) do
      add :failure_class, :text
    end

    create index(:outbound_delivery_logs, [:subscription_id, :created_at],
             name: "outbound_logs_sub_response_health_idx",
             where: "status = 'success' OR failure_class = 'response'",
             include: ["status"]
           )

    create index(:outbound_delivery_logs, [:connection_id, :created_at],
             name: "outbound_logs_conn_transport_health_idx",
             where: "status = 'success' OR failure_class = 'transport'",
             include: ["status"]
           )
  end

  def down do
    drop_if_exists index(:outbound_delivery_logs, [:connection_id, :created_at],
                     name: "outbound_logs_conn_transport_health_idx"
                   )

    drop_if_exists index(:outbound_delivery_logs, [:subscription_id, :created_at],
                     name: "outbound_logs_sub_response_health_idx"
                   )

    alter table(:outbound_delivery_logs) do
      remove :failure_class
    end
  end
end
