defmodule Example.Repo.Migrations.AddDeliveredAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_event_deliveries) do
      add :delivered_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:outbound_event_deliveries) do
      remove :delivered_at
    end
  end
end
