defmodule Example.Repo.Migrations.AddSuspensionSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_subscriptions) do
      add :suspension_source, :text
    end

    alter table(:outbound_connections) do
      add :suspension_source, :text
    end
  end

  def down do
    alter table(:outbound_connections) do
      remove :suspension_source
    end

    alter table(:outbound_subscriptions) do
      remove :suspension_source
    end
  end
end
