defmodule Example.Repo.Migrations.AddTransformRuntime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_subscriptions) do
      add :transform_runtime, :text, null: false, default: "lua"
    end
  end

  def down do
    alter table(:outbound_subscriptions) do
      remove :transform_runtime
    end
  end
end
