defmodule Example.Repo.Migrations.RemoveTransportColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_integrations) do
      remove :transport
    end
  end

  def down do
    alter table(:outbound_integrations) do
      add :transport, :text, null: false, default: "http"
    end
  end
end
