defmodule Example.Repo.Migrations.AddDedupBaselineIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:outbound_event_deliveries, [:subscription_id, :event_key, :event_id],
             name: "idx_event_deliveries_dedup_baseline",
             where: "state = 'delivered'",
             include: ["body_hash"]
           )
  end

  def down do
    drop_if_exists index(:outbound_event_deliveries, [:subscription_id, :event_key, :event_id],
                     name: "idx_event_deliveries_dedup_baseline"
                   )
  end
end
