defmodule Example.Repo.Migrations.AddTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:widgets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :stock, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :hashed_password, :text, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:stock_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :widget_id, :uuid, null: false
      add :quantity, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sku, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:outbound_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :event_type, :text, null: false
      add :version, :bigint, null: false
      add :transform_script, :text
      add :notify_on_every_change, :boolean, default: false
      add :route_config, :map
      add :consecutive_failures, :bigint, null: false, default: 0
      add :active, :boolean, default: true
      add :suspended, :boolean, default: false
      add :suspended_at, :utc_datetime_usec
      add :suspension_reason, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :connection_id, :uuid, null: false
    end

    create index(:outbound_subscriptions, [:connection_id, :event_type, :version])

    create index(:outbound_subscriptions, [:event_type])

    create index(:outbound_subscriptions, [:connection_id])

    create table(:outbound_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :event_type, :text, null: false
      add :version, :bigint, null: false
      add :event_key, :text, null: false
      add :source_resource, :text, null: false
      add :source_resource_id, :text, null: false
      add :source_action, :text, null: false
      add :data, :map, null: false
      add :dispatched_at, :utc_datetime_usec
      add :claimed_at, :utc_datetime_usec
      add :dispatch_attempts, :bigint, null: false, default: 0
      add :dispatch_error, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:outbound_events, [:created_at],
             name: "idx_events_retention",
             where: "dispatched_at IS NOT NULL"
           )

    create index(:outbound_events, [:id],
             name: "idx_events_outbox_claim",
             where: "dispatched_at IS NULL"
           )

    create index(:outbound_events, [:event_key, :id],
             name: "idx_events_undispatched_lane",
             where: "dispatched_at IS NULL"
           )

    create index(:outbound_events, [:source_resource, :source_resource_id])

    create index(:outbound_events, [:event_type, :version])

    create table(:outbound_event_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :event_type, :text, null: false
      add :version, :bigint, null: false
      add :event_key, :text, null: false
      add :delivery, :map
      add :state, :text, null: false, default: "pending"
      add :attempts, :bigint, null: false, default: 0
      add :last_error, :text
      add :delivery_metadata, :map
      add :claimed_at, :utc_datetime_usec
      add :next_attempt_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:outbound_events,
            column: :id,
            name: "outbound_event_deliveries_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :restrict
          ),
          null: false

      add :subscription_id,
          references(:outbound_subscriptions,
            column: :id,
            name: "outbound_event_deliveries_subscription_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :restrict
          ),
          null: false

      add :connection_id, :uuid, null: false
    end

    create index(:outbound_event_deliveries, [:connection_id, :event_id],
             name: "idx_event_deliveries_delivery_claim",
             where: "state = 'scheduled'"
           )

    create index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
             name: "idx_event_deliveries_schedulable_lane",
             where: "state IN ('pending', 'parked')"
           )

    create index(:outbound_event_deliveries, [:connection_id, :event_key],
             name: "idx_one_scheduled_per_connection_event_key",
             unique: true,
             where: "state = 'scheduled'"
           )

    create index(:outbound_event_deliveries, [:connection_id])

    create index(:outbound_event_deliveries, [:state, :updated_at])

    create index(:outbound_event_deliveries, [:subscription_id, :event_key, :state])

    create index(:outbound_event_deliveries, [:connection_id, :event_key, :state])

    create index(:outbound_event_deliveries, [:subscription_id, :state])

    create index(:outbound_event_deliveries, [:event_id])

    create table(:outbound_delivery_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :event_type, :text, null: false
      add :version, :bigint
      add :event_key, :text
      add :request_payload, :map
      add :response_status, :bigint
      add :response_body, :text
      add :error_message, :text
      add :kafka_offset, :bigint
      add :kafka_partition, :bigint
      add :duration_ms, :bigint
      add :status, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_id,
          references(:outbound_subscriptions,
            column: :id,
            name: "outbound_delivery_logs_subscription_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :restrict
          ),
          null: false

      add :connection_id, :uuid, null: false
      add :event_delivery_id, :uuid
    end

    create index(:outbound_delivery_logs, [:connection_id, :event_key, :created_at])

    create index(:outbound_delivery_logs, [:created_at])

    create index(:outbound_delivery_logs, [:event_delivery_id])

    create index(:outbound_delivery_logs, [:connection_id])

    create index(:outbound_delivery_logs, [:subscription_id])

    create table(:outbound_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:outbound_subscriptions) do
      modify :connection_id,
             references(:outbound_connections,
               column: :id,
               name: "outbound_subscriptions_connection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end

    alter table(:outbound_event_deliveries) do
      modify :connection_id,
             references(:outbound_connections,
               column: :id,
               name: "outbound_event_deliveries_connection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end

    create unique_index(:outbound_event_deliveries, [:event_id, :subscription_id],
             name: "outbound_event_deliveries_unique_event_subscription_index"
           )

    alter table(:outbound_delivery_logs) do
      modify :connection_id,
             references(:outbound_connections,
               column: :id,
               name: "outbound_delivery_logs_connection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :restrict
             )
    end

    alter table(:outbound_connections) do
      add :name, :text, null: false
      add :transport_config, :map, null: false
      add :consecutive_failures, :bigint, null: false, default: 0
      add :active, :boolean, default: true
      add :suspended, :boolean, default: false
      add :suspended_at, :utc_datetime_usec
      add :suspension_reason, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "outbound_connections_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ),
          null: false
    end

    create index(:outbound_connections, [:owner_id])

    create index(:outbound_connections, [:active])

    create unique_index(:outbound_connections, [:name], name: "outbound_connections_name_index")
  end

  def down do
    drop_if_exists unique_index(:outbound_connections, [:name],
                     name: "outbound_connections_name_index"
                   )

    drop constraint(:outbound_connections, "outbound_connections_owner_id_fkey")

    drop_if_exists index(:outbound_connections, [:active])

    drop_if_exists index(:outbound_connections, [:owner_id])

    alter table(:outbound_connections) do
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :suspension_reason
      remove :suspended_at
      remove :suspended
      remove :active
      remove :consecutive_failures
      remove :transport_config
      remove :name
    end

    drop constraint(:outbound_delivery_logs, "outbound_delivery_logs_connection_id_fkey")

    alter table(:outbound_delivery_logs) do
      modify :connection_id, :uuid
    end

    drop_if_exists unique_index(:outbound_event_deliveries, [:event_id, :subscription_id],
                     name: "outbound_event_deliveries_unique_event_subscription_index"
                   )

    drop constraint(:outbound_event_deliveries, "outbound_event_deliveries_connection_id_fkey")

    alter table(:outbound_event_deliveries) do
      modify :connection_id, :uuid
    end

    drop constraint(:outbound_subscriptions, "outbound_subscriptions_connection_id_fkey")

    alter table(:outbound_subscriptions) do
      modify :connection_id, :uuid
    end

    drop table(:outbound_connections)

    drop constraint(:outbound_delivery_logs, "outbound_delivery_logs_subscription_id_fkey")

    drop_if_exists index(:outbound_delivery_logs, [:subscription_id])

    drop_if_exists index(:outbound_delivery_logs, [:connection_id])

    drop_if_exists index(:outbound_delivery_logs, [:event_delivery_id])

    drop_if_exists index(:outbound_delivery_logs, [:created_at])

    drop_if_exists index(:outbound_delivery_logs, [:connection_id, :event_key, :created_at])

    drop table(:outbound_delivery_logs)

    drop constraint(:outbound_event_deliveries, "outbound_event_deliveries_event_id_fkey")

    drop constraint(:outbound_event_deliveries, "outbound_event_deliveries_subscription_id_fkey")

    drop_if_exists index(:outbound_event_deliveries, [:event_id])

    drop_if_exists index(:outbound_event_deliveries, [:subscription_id, :state])

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key, :state])

    drop_if_exists index(:outbound_event_deliveries, [:subscription_id, :event_key, :state])

    drop_if_exists index(:outbound_event_deliveries, [:state, :updated_at])

    drop_if_exists index(:outbound_event_deliveries, [:connection_id])

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key],
                     name: "idx_one_scheduled_per_connection_event_key"
                   )

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_key, :event_id],
                     name: "idx_event_deliveries_schedulable_lane"
                   )

    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_id],
                     name: "idx_event_deliveries_delivery_claim"
                   )

    drop table(:outbound_event_deliveries)

    drop_if_exists index(:outbound_events, [:event_type, :version])

    drop_if_exists index(:outbound_events, [:source_resource, :source_resource_id])

    drop_if_exists index(:outbound_events, [:event_key, :id],
                     name: "idx_events_undispatched_lane"
                   )

    drop_if_exists index(:outbound_events, [:id], name: "idx_events_outbox_claim")

    drop_if_exists index(:outbound_events, [:created_at], name: "idx_events_retention")

    drop table(:outbound_events)

    drop_if_exists index(:outbound_subscriptions, [:connection_id])

    drop_if_exists index(:outbound_subscriptions, [:event_type])

    drop_if_exists index(:outbound_subscriptions, [:connection_id, :event_type, :version])

    drop table(:outbound_subscriptions)

    drop table(:products)

    drop table(:stock_items)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop table(:widgets)
  end
end
