defmodule Example.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:integration_delivery_logs) do
      add :kafka_offset, :bigint
      add :kafka_partition, :bigint
    end
  end

  def down do
    alter table(:integration_delivery_logs) do
      remove :kafka_partition
      remove :kafka_offset
    end
  end
end
