defmodule Example.Repo.Migrations.AddInboundCommandExecutions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :partner_ref, :text
    end

    create table(:inbound_command_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :command_source, :text, null: false
      add :command_id, :text, null: false
      add :command_type, :text, null: false
      add :raw_command_type, :text, null: false
      add :transport, :text, null: false
      add :partition_key, :text
      add :payload, :map
      add :raw, :map
      add :result, :map
      add :state, :text, null: false, default: "pending"
      add :error, :text
      add :attempts, :bigint, null: false, default: 0
      add :claimed_at, :utc_datetime_usec
      add :next_attempt_at, :utc_datetime_usec
      add :applied_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "inbound_command_executions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :restrict
          )

      add :source_delivery_id,
          references(:outbound_event_deliveries,
            column: :id,
            name: "inbound_command_executions_source_delivery_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :restrict
          )
    end

    create index(:inbound_command_executions, [:partition_key, :id],
             name: "idx_command_executions_ordering_lane",
             where: "state IN ('pending', 'parked')"
           )

    create index(:inbound_command_executions, [:id],
             name: "idx_command_executions_claim",
             where: "state = 'pending'"
           )

    create index(:inbound_command_executions, [:state, :updated_at])

    create index(:inbound_command_executions, [:command_type, :state])

    create index(:inbound_command_executions, [:source_delivery_id])

    create unique_index(:inbound_command_executions, [:command_source, :command_id],
             name: "inbound_command_executions_unique_command_identity_index"
           )
  end

  def down do
    drop constraint(:inbound_command_executions, "inbound_command_executions_actor_id_fkey")

    drop constraint(
           :inbound_command_executions,
           "inbound_command_executions_source_delivery_id_fkey"
         )

    drop_if_exists unique_index(:inbound_command_executions, [:command_source, :command_id],
                     name: "inbound_command_executions_unique_command_identity_index"
                   )

    drop_if_exists index(:inbound_command_executions, [:source_delivery_id])

    drop_if_exists index(:inbound_command_executions, [:command_type, :state])

    drop_if_exists index(:inbound_command_executions, [:state, :updated_at])

    drop_if_exists index(:inbound_command_executions, [:id], name: "idx_command_executions_claim")

    drop_if_exists index(:inbound_command_executions, [:partition_key, :id],
                     name: "idx_command_executions_ordering_lane"
                   )

    drop table(:inbound_command_executions)

    alter table(:products) do
      remove :partner_ref
    end
  end
end
