defmodule Example.Repo.Migrations.AddEventDeliveryTerminalReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_event_deliveries) do
      add :terminal_reason, :text
    end
  end

  def down do
    alter table(:outbound_event_deliveries) do
      remove :terminal_reason
    end
  end
end
