defmodule Example.Repo.Migrations.DeliveryClaimEventIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:outbound_event_deliveries, [:connection_id, :event_id],
                     name: "idx_event_deliveries_delivery_claim"
                   )

    create index(:outbound_event_deliveries, [:event_id],
             name: "idx_event_deliveries_delivery_claim",
             where: "state = 'scheduled'"
           )
  end

  def down do
    drop_if_exists index(:outbound_event_deliveries, [:event_id],
                     name: "idx_event_deliveries_delivery_claim"
                   )

    create index(:outbound_event_deliveries, [:connection_id, :event_id],
             name: "idx_event_deliveries_delivery_claim",
             where: "state = 'scheduled'"
           )
  end
end
