defmodule Example.Repo.Migrations.AddDefaultTransformScript do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_integrations) do
      modify :transform_script, :text, default: "result = event"
    end
  end

  def down do
    alter table(:outbound_integrations) do
      modify :transform_script, :text, default: nil
    end
  end
end
