defmodule Example.Repo.Migrations.RenameCreatedAtToInsertedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:outbound_connections), :created_at, to: :inserted_at

    drop_if_exists index(:outbound_delivery_logs, [:created_at])

    drop_if_exists index(:outbound_delivery_logs, [:connection_id, :event_key, :created_at])

    rename table(:outbound_delivery_logs), :created_at, to: :inserted_at

    create index(:outbound_delivery_logs, [:inserted_at])

    create index(:outbound_delivery_logs, [:connection_id, :event_key, :inserted_at])

    rename table(:outbound_event_deliveries), :created_at, to: :inserted_at

    drop_if_exists index(:outbound_events, [:created_at], name: "idx_events_retention")

    rename table(:outbound_events), :created_at, to: :inserted_at

    create index(:outbound_events, [:inserted_at],
             name: "idx_events_retention",
             where: "dispatched_at IS NOT NULL"
           )

    rename table(:outbound_subscriptions), :created_at, to: :inserted_at
  end

  def down do
    rename table(:outbound_subscriptions), :inserted_at, to: :created_at

    drop_if_exists index(:outbound_events, [:inserted_at], name: "idx_events_retention")

    rename table(:outbound_events), :inserted_at, to: :created_at

    create index(:outbound_events, [:created_at],
             name: "idx_events_retention",
             where: "dispatched_at IS NOT NULL"
           )

    rename table(:outbound_event_deliveries), :inserted_at, to: :created_at

    drop_if_exists index(:outbound_delivery_logs, [:connection_id, :event_key, :inserted_at])

    drop_if_exists index(:outbound_delivery_logs, [:inserted_at])

    rename table(:outbound_delivery_logs), :inserted_at, to: :created_at

    create index(:outbound_delivery_logs, [:connection_id, :event_key, :created_at])

    create index(:outbound_delivery_logs, [:created_at])

    rename table(:outbound_connections), :inserted_at, to: :created_at
  end
end
