defmodule Example.Repo.Migrations.AddDispatchTerminalReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_events) do
      add :dispatch_terminal_reason, :text
    end
  end

  def down do
    alter table(:outbound_events) do
      remove :dispatch_terminal_reason
    end
  end
end
