defmodule Example.Repo.Migrations.AddTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :hashed_password, :text, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sku, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:outbound_integrations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :resource, :text, null: false
      add :actions, {:array, :text}, null: false, default: []
      add :schema_version, :bigint, null: false
      add :transport, :text, null: false, default: "http"
      add :transport_config, :map, null: false
      add :transform_script, :text, null: false
      add :consecutive_failures, :bigint, null: false, default: 0
      add :deactivation_reason, :text
      add :active, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "outbound_integrations_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          ),
          null: false
    end

    create index(:outbound_integrations, [:owner_id])

    create index(:outbound_integrations, [:resource, :active])

    create unique_index(:outbound_integrations, [:name], name: "outbound_integrations_name_index")

    create table(:integration_delivery_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :event_id, :uuid, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :schema_version, :bigint
      add :resource_id, :uuid, null: false
      add :request_payload, :map
      add :response_status, :bigint
      add :response_body, :text
      add :error_message, :text
      add :duration_ms, :bigint
      add :status, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :outbound_integration_id,
          references(:outbound_integrations,
            column: :id,
            name: "integration_delivery_logs_outbound_integration_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :restrict
          ),
          null: false
    end

    create index(:integration_delivery_logs, [:outbound_integration_id, :resource_id, :created_at])

    create index(:integration_delivery_logs, [:created_at])

    create index(:integration_delivery_logs, [:event_id])

    create index(:integration_delivery_logs, [:outbound_integration_id])
  end

  def down do
    drop constraint(
           :integration_delivery_logs,
           "integration_delivery_logs_outbound_integration_id_fkey"
         )

    drop_if_exists index(:integration_delivery_logs, [:outbound_integration_id])

    drop_if_exists index(:integration_delivery_logs, [:event_id])

    drop_if_exists index(:integration_delivery_logs, [:created_at])

    drop_if_exists index(:integration_delivery_logs, [
                     :outbound_integration_id,
                     :resource_id,
                     :created_at
                   ])

    drop table(:integration_delivery_logs)

    drop_if_exists unique_index(:outbound_integrations, [:name],
                     name: "outbound_integrations_name_index"
                   )

    drop constraint(:outbound_integrations, "outbound_integrations_owner_id_fkey")

    drop_if_exists index(:outbound_integrations, [:resource, :active])

    drop_if_exists index(:outbound_integrations, [:owner_id])

    drop table(:outbound_integrations)

    drop table(:products)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
