defmodule Example.Repo.Migrations.RenameTransformScriptToTransformSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:outbound_subscriptions), :transform_script, to: :transform_source
  end

  def down do
    rename table(:outbound_subscriptions), :transform_source, to: :transform_script
  end
end
